version: "3.8"

services:
  corrm:
    # image: torch2.1.1-yh:v250816
    image: cuda121-corrmatch:v2
    shm_size: 28g
    volumes:
      - /mnt/c/Users/yonghyun/Desktop/dev/CorrMatch:/home/dev/CorrMatch
      - /mnt/c/Users/yonghyun/Desktop/segmentation_datasets/cityscapes:/home/dev/Data
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro

    working_dir: /home/dev/CorrMatch
    command: /bin/bash -c "service ssh restart && tail -f /dev/null"
    restart: no
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]


# version: "3.8"

# services:
#   corrmatch:
#     image: cud121-corrmatch
#     container_name: corrmatch
#     runtime: nvidia

#     # GPU 사용 — compose v2에서 지원
#     gpus: all
#     environment:
#       - NVIDIA_VISIBLE_DEVICES=all
#       - NVIDIA_DRIVER_CAPABILITIES=compute,utility
#       - LD_LIBRARY_PATH=/usr/lib/wsl/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64

#     volumes:
#       - /mnt/c/Users/yonghyun/Desktop/dev/CorrMatch:/home/dev/CorrMatch
#       - /mnt/c/Users/yonghyun/Desktop/segmentation_datasets/cityscapes:/home/dev/Data

#     working_dir: /home/dev/CorrMatch

#     # SSH 열어두고 컨테이너 유지
#     ports:
#       - "2222:22"
#     command: ["/usr/sbin/sshd", "-D"]

#     # # 학습 시 편의 옵션 (선택)
#     # shm_size: "16g"
#     # ipc: host
#     # tty: true
#     # stdin_open: true

#     restart: "no"



# version: "3.8"

# services:
#   corrmatch:
#     image: cuda121-corrmatch:v2
#     container_name: corrmatch
#     # runtime: nvidia
#     # gpus: all

#     environment:
#       # NVIDIA 환경 변수
#       - NVIDIA_VISIBLE_DEVICES=all
#       - NVIDIA_DRIVER_CAPABILITIES=compute,utility
#       - CUDA_HOME=/usr/local/cuda
#       - LD_LIBRARY_PATH=/usr/lib/wsl/lib:/usr/lib/wsl/drivers:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
#       - PATH=/usr/local/cuda/bin:${PATH}

#     volumes:
#       # 코드 및 데이터 경로
#       - /mnt/c/Users/yonghyun/Desktop/dev/CorrMatch:/home/dev/CorrMatch
#       - /mnt/c/Users/yonghyun/Desktop/segmentation_datasets/cityscapes:/home/dev/Data
#       # 드라이버 경로 마운트 (WSL2 전용)
#       - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
#       - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro

#     working_dir: /home/dev/CorrMatch

#     ports:
#       - "2222:22"

#     # command: ["/usr/sbin/sshd", "-D"]
#     command: /bin/bash -c "service ssh restart && tail -f /dev/null"

#     # 편의 옵션
#     # shm_size: "16g"
#     # ipc: host
#     # tty: true
#     # stdin_open: true

#     restart: "no"

#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               device_ids: ['0']
#               capabilities: [gpu]