# arguments for dataset
dataset: cityscapes
nclass: 19
# crop_size: 801
crop_size: 448
data_root: /home/dev/data

# arguments for training
epochs: 240
batch_size: 4
accumulation_steps: 4 
# lr: 0.005  # 4GPUs
lr: 0.00125  # 1GPUs
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 100000
conf_thresh: 0.0

# arguments for model
backbone: resnet101
# backbone: resnet50
multi_grid: False
replace_stride_with_dilation: [False, True, True]
dilations: [12, 24, 36]
# pretrain: False
pretrain: True
thresh_init: 0.85